import { documentTypeSchema, type DocumentType } from "../../shared/schemas/document-type.ts";
import { requestTemplateSchema, type RequestTemplate } from "../../shared/schemas/request.ts";

const SEED_CREATED_AT = "2026-01-01T00:00:00.000Z";

const rawSeedDocumentTypes = [
  {
    id: "dt-profit-loss",
    name: "Profit & loss statement",
    description: "Income statement showing revenue, expenses, and net income for a reporting period.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "business_name",
        label: "Business name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Legal or trade name shown in the statement header.",
      },
      {
        key: "period_start",
        label: "Period start",
        metadataType: "date" as const,
        dataType: "date" as const,
        required: true,
        description: "Start date of the income statement reporting period.",
      },
      {
        key: "period_end",
        label: "Period end",
        metadataType: "date" as const,
        dataType: "date" as const,
        required: true,
        description: "End date of the income statement reporting period.",
      },
      {
        key: "gross_receipts",
        label: "Gross receipts",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Total revenue or gross receipts line before cost of goods sold and expenses.",
      },
      {
        key: "total_expenses",
        label: "Total expenses",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Sum of all operating and other expenses for the period.",
      },
      {
        key: "net_income",
        label: "Net income",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Bottom-line net income or loss for the reporting period.",
      },
      {
        key: "officer_compensation",
        label: "Officer compensation",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Officer salaries and compensation expense line on the P&L.",
      },
      {
        key: "salaries_wages",
        label: "Salaries and wages",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Employee salaries and wages expense line on the income statement.",
      },
      {
        key: "rents",
        label: "Rents",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Rent expense line on the income statement.",
      },
      {
        key: "taxes_licenses",
        label: "Taxes and licenses",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Taxes and license expense line on the income statement.",
      },
      {
        key: "depreciation",
        label: "Depreciation",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Depreciation expense line on the income statement.",
      },
      {
        key: "advertising",
        label: "Advertising",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Advertising or marketing expense line on the income statement.",
      },
    ],
  },
  {
    id: "dt-balance-sheet",
    name: "Balance sheet",
    description: "Statement of financial position showing assets, liabilities, and equity as of a date.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "business_name",
        label: "Business name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Legal or trade name shown in the balance sheet header.",
      },
      {
        key: "period_end",
        label: "Period end",
        metadataType: "date" as const,
        dataType: "date" as const,
        required: true,
        description: "As-of date for the balance sheet snapshot.",
      },
      {
        key: "total_assets",
        label: "Total assets",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Total assets line at the bottom of the assets section.",
      },
      {
        key: "total_liabilities",
        label: "Total liabilities",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Total liabilities line at the bottom of the liabilities section.",
      },
      {
        key: "total_equity",
        label: "Total equity",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Total equity or net worth line on the balance sheet.",
      },
      {
        key: "cash",
        label: "Cash",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Cash and cash equivalents line under current assets.",
      },
      {
        key: "accounts_receivable",
        label: "Accounts receivable",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Accounts receivable or trade receivables line under current assets.",
      },
    ],
  },
  {
    id: "dt-trial-balance",
    name: "Trial balance",
    description: "Listing of general ledger account balances with total debits and credits.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "business_name",
        label: "Business name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Business name shown in the trial balance header.",
      },
      {
        key: "period_end",
        label: "Period end",
        metadataType: "date" as const,
        dataType: "date" as const,
        required: true,
        description: "As-of date for the trial balance listing.",
      },
      {
        key: "total_debits",
        label: "Total debits",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Sum of all debit column balances on the trial balance.",
      },
      {
        key: "total_credits",
        label: "Total credits",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Sum of all credit column balances on the trial balance.",
      },
    ],
  },
  {
    id: "dt-941",
    name: "Form 941",
    description: "Employer's quarterly federal tax return reporting payroll taxes and wages.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "business_name",
        label: "Business name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Employer name field at the top of Form 941.",
      },
      {
        key: "employer_ein",
        label: "Employer EIN",
        metadataType: "ein-tin" as const,
        dataType: "string" as const,
        required: true,
        regex: "^\\d{2}-\\d{7}$",
        description: "Employer identification number in the EIN field on Form 941.",
      },
      {
        key: "quarter",
        label: "Quarter",
        metadataType: "identifier" as const,
        dataType: "string" as const,
        required: true,
        regex: "^Q[1-4]$",
        description: "Reporting quarter indicator (Q1, Q2, Q3, or Q4) for this 941 return.",
      },
      {
        key: "tax_year",
        label: "Tax year",
        metadataType: "quantity" as const,
        dataType: "int" as const,
        required: true,
        description: "Calendar year printed on the Form 941 header.",
      },
      {
        key: "wages_tips_compensation",
        label: "Wages, tips, and compensation",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Line 2 — total wages, tips, and other compensation for the quarter.",
      },
      {
        key: "federal_tax_withheld",
        label: "Federal income tax withheld",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: false,
        description: "Line 3 — federal income tax withheld from employee wages for the quarter.",
      },
    ],
  },
  {
    id: "dt-1099-nec",
    name: "Form 1099-NEC",
    description: "Nonemployee compensation information return for independent contractors.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "payer_name",
        label: "Payer name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Payer's name shown in the upper-left section of Form 1099-NEC.",
      },
      {
        key: "payer_tin",
        label: "Payer TIN",
        metadataType: "ein-tin" as const,
        dataType: "string" as const,
        required: true,
        regex: "^\\d{2}-\\d{7}$",
        description: "Payer's taxpayer identification number in the TIN field on the form.",
      },
      {
        key: "recipient_name",
        label: "Recipient name",
        metadataType: "person-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Recipient's name in the payee section of Form 1099-NEC.",
      },
      {
        key: "recipient_tin",
        label: "Recipient TIN",
        metadataType: "ein-tin" as const,
        dataType: "string" as const,
        required: true,
        regex: "^(\\d{2}-\\d{7}|\\d{3}-\\d{2}-\\d{4})$",
        description: "Recipient's TIN in the recipient identification field (EIN or SSN format).",
      },
      {
        key: "nonemployee_compensation",
        label: "Nonemployee compensation",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Box 1 — nonemployee compensation amount paid to the recipient.",
      },
      {
        key: "tax_year",
        label: "Tax year",
        metadataType: "quantity" as const,
        dataType: "int" as const,
        required: true,
        description: "Tax year printed in the form header or year box.",
      },
    ],
  },
  {
    id: "dt-k1-1065",
    name: "Schedule K-1 (Form 1065)",
    description: "Partner's share of income, deductions, and credits from a partnership return.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "partnership_name",
        label: "Partnership name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Partnership name in Part I of Schedule K-1 (Form 1065).",
      },
      {
        key: "partnership_ein",
        label: "Partnership EIN",
        metadataType: "ein-tin" as const,
        dataType: "string" as const,
        required: true,
        regex: "^\\d{2}-\\d{7}$",
        description: "Partnership employer identification number in Part I of the K-1.",
      },
      {
        key: "partner_name",
        label: "Partner name",
        metadataType: "person-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Partner's name in Part II of Schedule K-1 (Form 1065).",
      },
      {
        key: "ordinary_business_income",
        label: "Ordinary business income",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Box 1 — ordinary business income (loss) allocated to the partner.",
      },
      {
        key: "tax_year",
        label: "Tax year",
        metadataType: "quantity" as const,
        dataType: "int" as const,
        required: true,
        description: "Tax year printed in the Schedule K-1 header.",
      },
    ],
  },
  {
    id: "dt-k1-1120s",
    name: "Schedule K-1 (Form 1120-S)",
    description: "Shareholder's share of income, deductions, and credits from an S corporation return.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "corporation_name",
        label: "Corporation name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "S corporation name in Part I of Schedule K-1 (Form 1120-S).",
      },
      {
        key: "corporation_ein",
        label: "Corporation EIN",
        metadataType: "ein-tin" as const,
        dataType: "string" as const,
        required: true,
        regex: "^\\d{2}-\\d{7}$",
        description: "Corporation employer identification number in Part I of the K-1.",
      },
      {
        key: "shareholder_name",
        label: "Shareholder name",
        metadataType: "person-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Shareholder's name in Part II of Schedule K-1 (Form 1120-S).",
      },
      {
        key: "ordinary_business_income",
        label: "Ordinary business income",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Box 1 — ordinary business income (loss) allocated to the shareholder.",
      },
      {
        key: "tax_year",
        label: "Tax year",
        metadataType: "quantity" as const,
        dataType: "int" as const,
        required: true,
        description: "Tax year printed in the Schedule K-1 header.",
      },
    ],
  },
  {
    id: "dt-fixed-assets",
    name: "Fixed asset schedule",
    description: "Depreciation schedule listing fixed assets, cost basis, and accumulated depreciation.",
    active: true,
    createdBy: "seed" as const,
    createdAt: SEED_CREATED_AT,
    fields: [
      {
        key: "business_name",
        label: "Business name",
        metadataType: "business-name" as const,
        dataType: "string" as const,
        required: true,
        description: "Business name shown in the fixed asset schedule header.",
      },
      {
        key: "period_end",
        label: "Period end",
        metadataType: "date" as const,
        dataType: "date" as const,
        required: true,
        description: "As-of date for the fixed asset depreciation schedule.",
      },
      {
        key: "total_cost_basis",
        label: "Total cost basis",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Total original cost basis of all listed fixed assets.",
      },
      {
        key: "total_accumulated_depreciation",
        label: "Total accumulated depreciation",
        metadataType: "total" as const,
        dataType: "double" as const,
        required: true,
        description: "Total accumulated depreciation across all listed fixed assets.",
      },
      {
        key: "current_year_depreciation",
        label: "Current year depreciation",
        metadataType: "dollar-amount" as const,
        dataType: "double" as const,
        required: true,
        description: "Total depreciation expense for the current tax year on the schedule.",
      },
    ],
  },
];

const rawSeedRequestTemplates = [
  {
    id: "tpl-1120s",
    filingType: "1120-S" as const,
    items: [
      {
        title: "Profit & loss statement",
        description: "Current-year income statement for the S corporation.",
        documentTypeId: "dt-profit-loss",
        required: true,
      },
      {
        title: "Balance sheet",
        description: "Year-end balance sheet for the S corporation.",
        documentTypeId: "dt-balance-sheet",
        required: true,
      },
      {
        title: "Trial balance",
        description: "Year-end trial balance supporting the financial statements.",
        documentTypeId: "dt-trial-balance",
        required: false,
      },
      {
        title: "Quarterly 941s",
        description: "All four quarterly 941s",
        documentTypeId: "dt-941",
        required: true,
      },
      {
        title: "1099-NEC forms",
        description: "Nonemployee compensation forms issued to contractors.",
        documentTypeId: "dt-1099-nec",
        required: false,
      },
      {
        title: "Fixed asset schedule",
        description: "Depreciation schedule for fixed assets.",
        documentTypeId: "dt-fixed-assets",
        required: false,
      },
      {
        title: "Prior-year K-1s",
        description: "Prior-year K-1s",
        documentTypeId: "dt-k1-1120s",
        required: false,
      },
    ],
  },
  {
    id: "tpl-1065",
    filingType: "1065" as const,
    items: [
      {
        title: "Profit & loss statement",
        description: "Current-year income statement for the partnership.",
        documentTypeId: "dt-profit-loss",
        required: true,
      },
      {
        title: "Balance sheet",
        description: "Year-end balance sheet for the partnership.",
        documentTypeId: "dt-balance-sheet",
        required: true,
      },
      {
        title: "Trial balance",
        description: "Year-end trial balance supporting the financial statements.",
        documentTypeId: "dt-trial-balance",
        required: false,
      },
      {
        title: "Quarterly 941s",
        description: "All four quarterly 941s",
        documentTypeId: "dt-941",
        required: true,
      },
      {
        title: "1099-NEC forms",
        description: "Nonemployee compensation forms issued to contractors.",
        documentTypeId: "dt-1099-nec",
        required: false,
      },
      {
        title: "Fixed asset schedule",
        description: "Depreciation schedule for fixed assets.",
        documentTypeId: "dt-fixed-assets",
        required: false,
      },
      {
        title: "Prior-year partner K-1s",
        description: "Prior-year partner K-1s",
        documentTypeId: "dt-k1-1065",
        required: true,
      },
    ],
  },
];

export const seedDocumentTypes: DocumentType[] = rawSeedDocumentTypes.map((dt) =>
  documentTypeSchema.parse(dt),
);

export const seedRequestTemplates: RequestTemplate[] = rawSeedRequestTemplates.map((tpl) =>
  requestTemplateSchema.parse(tpl),
);
