import {
  clientRowSchema,
  documentRowSchema,
  inboxItemSchema,
  reviewRowSchema,
  type ClientRow,
  type DocumentRow,
  type InboxItem,
  type ReviewRow,
} from "../../shared/schemas/shell.ts";

export const documents: DocumentRow[] = [
  documentRowSchema.parse({
    id: "doc-w2-northwind",
    name: "2025 W-2",
    type: "W-2",
    client: "Northwind Partners",
    clientMeta: "Partnership · Boston",
    date: "Mar 12, 2026",
    status: "needs-review",
    statusLabel: "Needs review",
    initials: "NP",
  }),
  documentRowSchema.parse({
    id: "doc-1099-acme",
    name: "1099-NEC batch",
    type: "1099-NEC",
    client: "Acme Holdings",
    clientMeta: "S corporation · Austin",
    date: "Mar 9, 2026",
    status: "missing-items",
    statusLabel: "Missing items",
    initials: "AH",
  }),
  documentRowSchema.parse({
    id: "doc-k1-harbor",
    name: "K-1 package",
    type: "K-1",
    client: "Harbor LLC",
    clientMeta: "LLC · Seattle",
    date: "Mar 4, 2026",
    status: "pending",
    statusLabel: "Pending review",
    initials: "HL",
  }),
  documentRowSchema.parse({
    id: "doc-w2-lumen",
    name: "2025 W-2",
    type: "W-2",
    client: "Lumen Studio",
    clientMeta: "Sole prop · Denver",
    date: "Feb 28, 2026",
    status: "trusted",
    statusLabel: "Trusted",
    initials: "LS",
  }),
];

export const reviewQueue: ReviewRow[] = [
  reviewRowSchema.parse({
    id: "rev-1",
    name: "2025 W-2",
    type: "W-2",
    client: "Northwind Partners",
    clientMeta: "Partnership · Boston",
    date: "Mar 12, 2026",
    amountLabel: "Wages $186,400",
    category: "Compensation",
    queue: "needs-review",
    queueLabel: "Needs review",
  }),
  reviewRowSchema.parse({
    id: "rev-2",
    name: "1099-NEC batch",
    type: "1099-NEC",
    client: "Acme Holdings",
    clientMeta: "S corporation · Austin",
    date: "Mar 9, 2026",
    amountLabel: "Nonemployee $42,110",
    category: "Contract labor",
    queue: "waiting",
    queueLabel: "Waiting for client",
  }),
  reviewRowSchema.parse({
    id: "rev-3",
    name: "K-1 package",
    type: "K-1",
    client: "Harbor LLC",
    clientMeta: "LLC · Seattle",
    date: "Mar 4, 2026",
    amountLabel: "Ordinary income $91,250",
    category: "Passthrough",
    queue: "ready",
    queueLabel: "Ready to export",
  }),
];

export const clients: ClientRow[] = [
  clientRowSchema.parse({
    id: "client-northwind",
    name: "Northwind Partners",
    email: "books@northwind.test",
    role: "Partnership",
    firm: "Northwind Partners",
    location: "Boston",
    reviewer: "Alex Rivera",
    initials: "NP",
  }),
  clientRowSchema.parse({
    id: "client-acme",
    name: "Acme Holdings",
    email: "tax@acme.test",
    role: "S corporation",
    firm: "Acme Holdings",
    location: "Austin",
    reviewer: "Alex Rivera",
    initials: "AH",
  }),
  clientRowSchema.parse({
    id: "client-harbor",
    name: "Harbor LLC",
    email: "ops@harbor.test",
    role: "LLC",
    firm: "Harbor LLC",
    location: "Seattle",
    reviewer: "Jordan Lee",
    initials: "HL",
  }),
];

export const inboxItems: InboxItem[] = [
  inboxItemSchema.parse({
    id: "inbox-1",
    title: "W-2 wages need review",
    detail: "Northwind Partners · 3 fields unconfirmed",
    when: "2h ago",
  }),
  inboxItemSchema.parse({
    id: "inbox-2",
    title: "Missing employer EIN",
    detail: "Acme Holdings · 1099-NEC batch",
    when: "Yesterday",
  }),
  inboxItemSchema.parse({
    id: "inbox-3",
    title: "K-1 ready to mark trusted",
    detail: "Harbor LLC · ordinary income",
    when: "Mon",
  }),
];
